#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top_1.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_1.mk Vtop_1

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vtop_1
echo "\nSimulation completed"

