#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace full_f1.sv --exe full_f1_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vfull_f1.mk Vfull_f1

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vfull_f1
echo "\nSimulation completed"

